# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5561c67a8b48c261d3a9a2b1e8d22daa3aa094dae5155cce9e7decd4d06d82e8c8089ea4dc1b343fc000acb82fc68517092635fc7b887dfee8ed3b3b1d5de13

test:
  secret_key_base: c2b998b675c77910cf1f40387eb48924b3b5dfce889029862afea56247999aa8647b060aee08b972eadef0b7b7fee07fd411383b697d1c702b9504ba2114b019

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
